---
settings:
  name: ONTAP Hardware Systems
  search: ontap-systems,ontap-systems-upgrade,ontap-systems-switches,ontap-metrocluster
  internal:
    pdf_enabled: false
  prod:
    pdf_enabled: false
    harmony_enabled: false
  langs: zh-cn,us-en,ja-jp,ko-kr,zh-tw,de-de,es-es,fr-fr,it-it
sidebar:
  entries:
  - title: ONTAP硬件系统文档
    url: "/index.html"
